### PR TITLE
fix Incorrect merge

### PR DESCRIPTION
**Pull request by KavetiRohith**

### CODE REVIEW

**Review by kbuffardi — CHANGES_REQUESTED** [review]
Initially, I get: `401: Unable to connect to Nx Cloud.`

To fix that I run:
```
npm i -d @nrwl/nx-cloud
npm audit fix --force
nx g @nrwl/nx-cloud:init
```

Those get rid of that first error.

But when I run the seed-admin command, I get the same error again as listed in #29

**Comment by numan-7** [comment]
I'm getting a different type of cloud issue (see image).

Can you also upload your updated .env file to the drive as well or explain how you've set up your environment variables because I've tried to get them to recognized, but it's just not working.

image

**Comment by kbuffardi** [comment]
My `.env` is identical to the one in our shared drive. However, I added each of those environment variables to `~/.bashrc` with the exact `export` commands you provided in the README.

**Comment by kbuffardi** [comment]
@numan-7 I solved all my errors by killing my docker containers, uninstalling/reinstalling docker and docker-compose-plugin, then running `docker compose up -d` before using the seed command.

**Comment by numan-7** [comment]
> @numan-7 I solved all my errors by killing my docker containers, uninstalling/reinstalling docker and docker-compose-plugin, then running `docker compose up -d` before using the seed command.
> 
> I had an out-of-date version of docker on my (Linux Mint) machine so I think that was the culprit of my problems. If you run docker compose up _before_ the seed command, I think it'll work. Let us know if it doesn't.

Thanks, it says Admin Seeded now, not having any issues as of now

**Review by kbuffardi — APPROVED** [review]

**Pull request merged**
