### PR TITLE
Created Frontend for Attempt Model & Exercise Update

### PR DESCRIPTION
**Pull request by numan-7**
- Backend:
  - Created ``/attempts`` url for process attempts
  - Updated ``/exercises`` endpoint to accept `referenceTest` variable
 - Frontend:
   - Added reference test code field
   - Able to view demo in read page by clicking on it in the current demos section
   - Added attempts & linked to backend
     - Will show one exercise at a time, new exercise will appear after successful submission

### CODE REVIEW

**Comment by kbuffardi** [comment]
I'll hold-off on reviewing until we also have a corresponding PR for @KavetiRohith 's backend (or both integrated into a single PR). Just mark it as "Ready for review" once it's good for me to review.

**Comment by rkaveti-uptycs** [comment]
@numan-7 The backend work is done on this branch: https://github.com/codewit-us/codewit.us/tree/attempts-backend

**Comment by KavetiRohith** [comment]
@numan-7 the backend work is done on this branch: https://github.com/codewit-us/codewit.us/tree/attempts-backend.

**Comment by KavetiRohith** [comment]
Looks good to me.

**Review by KavetiRohith — APPROVED** [review]

**Pull request merged**
